export type PreferencePaneId =
  | 'general'
  | 'account'
  | 'security'
  | 'home-server'
  | 'vaults'
  | 'appearance'
  | 'backups'
  | 'plugins'
  | 'shortcuts'
  | 'accessibility'
  | 'get-free-month'
  | 'help-feedback'
